### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheDarkCode**
Fix typos.

### CODE REVIEW

**Review by codekoenig — CHANGES_REQUESTED** [review]
Thank you for taking the time to fix the typos! There's now an accidential linebreak in line 42 now that also replaced part of the word `Database`, though. I suppose you wanted to change something different here, please have a look.

**Comment by TheDarkCode** [comment]
Was an accidental keystroke that caused that. I fixed the PR.

Had noticed this repo before but not read into it until earlier tonight. I'm considering whether to do some pull requests - like addressing your partitioning issue for instance, versus doing a full rewrite to incorporate things I'm either working on or have written for 4.6 and need to migrate. Such as supporting streaming in the DocDB repository used for Identity, incorporating a sort-of dynamic data-masking for CC or SSN types like SQL, simplifying blob tie in for linked profile images and upload over API, Redis for session management and limited user graph, SQL Azure for aggregations and change log, and a way to use Table Storage for point reads of expanded data on a given user or for archived reports. Not to mention support tickets as a tie-in with Identity. There are some things I would do differently just looking at what is written, but then again, we are probably the only two people who would be putting up code on GitHub to extend DocDB Identity in Core to go beyond just feature parity with the SQL alternative.

**Review by codekoenig — APPROVED** [review]
Thank you

**Comment by codekoenig** [comment]
@TheDarkCode I'd appreciate any feedback to do things differently and PRs extending this project. I tried more or less to reach feature parity with the SQL provider for now just to get it working for a basic project, but as you have seen I will need things like partitioning support going forward, and also things like data masking or blob support are things I thought about too. Only thing I'd be hesitant about is to tie this project to other technologies like Redis or SQL Azure as I want it to be general purpose, but if those parts are pluggable, it would be fine. However, as you seem to have very specific requirements that might go well beyond what I need, it might be best to roll your own implementation anyway ... let me know if you're going that way, if possible I'd be glad to help out.

**Pull request merged**
