### PR TITLE
Updated DocmentDB version to 2.1.3. Fixes #24.

### LINKED ISSUE #24: Missing method exception after upgrading to SDK 2.1.3
MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Client.ResourceResponse`1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.IDocumentClient.ReadDocumentAsync(System.Uri, Microsoft.Azure.Documents.Client.RequestOptions)'.
AspNetCore.Identity.DocumentDb.Tools.DocumentDbExtensions.ReadDocumentAsync<T>(IDocumentClient client, Uri documentUri, RequestOptions requestOptions)
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
AspNetCore.Identity.DocumentDb.Tools.DocumentDbExtensions.ReadDocumentAsync<T>(IDocumentClient client, Uri documentUri, RequestOptions requestOptions)
AspNetCore.Identity.DocumentDb.Tools.DocumentDbExtensions.ReadDocumentAsync<T>(IDocumentClient client, Uri documentUri)
AspNetCore.Identity.DocumentDb.Stores.DocumentDbUserStore<TUser, TRole>.FindByIdAsync(string userId, CancellationToken cancellationToken)

### PR DESCRIPTION
**Pull request by RichMercer**
Updating the DocumentDB  version to 2.1.3 to fix #24 where there's a missing method exception.

### CODE REVIEW

**Comment by rhalaly** [comment]
@codekoenig When this PR will be merged?

**Comment by codekoenig** [comment]
Thanks a lot @RichMercer ! 
Done @rhalaly  ;)

**Comment by rhalaly** [comment]
@codekoenig Thank you! When this PR will be reflected in the Nuget?

**Comment by codekoenig** [comment]
@rhalaly The major version switch of Documentdb library requires a new major from this library too, so it requires a bit of work for review and testing and maybe some required adaptations with other open stuff. So it won't be today, but I'll try to get it on NuGet in the next couple of days.

**Comment by rhalaly** [comment]
Thank you! Can't wait to use it! :)

**Comment by rhalaly** [comment]
@codekoenig The NuGet package did not update yet, after more than a month after this PR was completed. When do you plan to update it?

**Pull request merged**
